environment:
  JAVA_HOME: C:\Program Files\Java\jdk1.8.0
os: Visual Studio 2017 # Windows Server 2016
install:
  - java -version
  - ./gradlew --version
build_script: false
test_script:
  - ./gradlew check -u -S --no-daemon --no-parallel
